// modules/readmeGenerator.js
import fs from "fs-extra";
import path from "path";

export async function generateReadme(destFolder) {
  const summary = path.join(destFolder, "projects_summary.csv");
  const readmePath = path.join(destFolder, "README.txt");

  let text = "PORTFOLIO PACKAGE\n";
  text += "=================\n\n";
  text += "Generated by Estimator AI V5\n";
  text += `Created: ${new Date().toLocaleString()}\n\n`;
  text += "Contents:\n";
  text += "- archive/ ............ full session archives\n";
  text += "- submittals/ ......... project PDFs, drawings, revision reports\n";
  text += "- projects.json ....... raw project data\n";
  text += "- projects_summary.csv  summary of all projects\n\n";

  if (await fs.pathExists(summary)) {
    const csv = await fs.readFile(summary, "utf8");
    const lines = csv.split("\n").slice(0, 6).join("\n");
    text += "Preview of summary data:\n";
    text += lines + "\n\n";
  }

  await fs.writeFile(readmePath, text);
  console.log(`[README] Created ${readmePath}`);
  return readmePath;
}
