// modules/submittalGenerator.js
import fs from "fs-extra";
import PDFDocument from "pdfkit";
import path from "path";

/**
 * Generates a simple submittal PDF for a given projectId.
 * Output: ./data/submittals/{projectId}_submittal.pdf
 */
export async function generateSubmittal(projectId, projectData = {}) {
  const outputDir = "./data/submittals";
  await fs.ensureDir(outputDir);

  const filename = path.join(outputDir, `${projectId}_submittal.pdf`);
  const doc = new PDFDocument({ margin: 50 });
  const stream = fs.createWriteStream(filename);
  doc.pipe(stream);

  // --- Header ---
  doc.fontSize(22).text("Estimator AI V5 – Project Submittal", { align: "center" });
  doc.moveDown();
  doc.fontSize(14).text(`Project ID: ${projectId}`);
  doc.text(`Generated on: ${new Date().toLocaleString()}`);
  doc.moveDown(1.5);

  // --- Project Info ---
  doc.fontSize(16).text("Project Information", { underline: true });
  doc.moveDown(0.5);
  Object.entries(projectData).forEach(([key, val]) => {
    doc.fontSize(12).text(`${key}: ${val}`);
  });
  doc.moveDown(1.5);

  // --- Materials / BOM (example only) ---
  doc.fontSize(16).text("Bill of Materials", { underline: true });
  const bom = projectData.materials || [];
  if (bom.length === 0) doc.text("No material data available.");
  else {
    bom.forEach((m, i) => {
      doc.fontSize(12).text(`${i + 1}. ${m.name} – ${m.qty} ${m.unit} @ $${m.cost}`);
    });
  }

  // --- QA Section ---
  doc.addPage();
  doc.fontSize(18).text("Quality Assurance Checklist", { align: "center" });
  doc.moveDown();
  const checklist = [
    "✅ Design criteria verified",
    "✅ Load calculations checked",
    "✅ Connections and hardware validated",
    "✅ Bracing and stability docs included",
  ];
  checklist.forEach((item) => doc.fontSize(12).text(item));

  // --- Footer ---
  doc.moveDown(3);
  doc.fontSize(10).text("Generated by Estimator AI V5", { align: "center", opacity: 0.6 });

  doc.end();

  await new Promise((resolve) => stream.on("finish", resolve));
  console.log(`[SUBMITTAL] Created ${filename}`);
  return filename;
}
