import fs from "fs-extra";
import { generateDrawings } from "../modules/drawingGenerator.js";
import { EmbedBuilder } from "discord.js";
import { requireMode } from "../modules/modeRouter.js";
import { logSessionEvent } from "../modules/sessionLogger.js";

export default {
  name: "drawing",
  description: "Generate DXF/SVG drawings (Designer-only)",
  async execute(message, args) {
    await requireMode("designer", message, async () => {
      try {
        if (!args.length) {
          return message.reply("❌ Usage: `!drawing <project_id>`");
        }

        const projectId = args[0].trim();
        const data = await fs.readJson("./data/projects.json").catch(() => ({}));
        const projects = Array.isArray(data.projects) ? data.projects : [];
        const project = projects.find((p) => p.id === projectId);
        if (!project) {
          return message.reply(`❌ Project not found: ${projectId}`);
        }

        const { dxfPath, svgPath } = await generateDrawings(project);

        const embed = new EmbedBuilder()
          .setColor(0x00b0f4)
          .setTitle("📐 Layout Drawings Generated")
          .addFields({ name: "Project", value: projectId, inline: false })
          .setTimestamp()
          .setFooter({ text: "Generated by Estimator AI V5" });

        await logSessionEvent(message.author.id, "Drawing Exported", {
          projectId,
          dxfPath,
          svgPath,
        });

        await message.reply({ embeds: [embed], files: [dxfPath, svgPath] });
      } catch (err) {
        console.error("[DRAWING ERROR]", err);
        message.reply("❌ Failed to generate drawings.");
      }
    });
  },
};
