import { generateSubmittal } from "../modules/submittalGenerator.js";
import fs from "fs-extra";
import { EmbedBuilder } from "discord.js";
import { logSessionEvent } from "../modules/sessionLogger.js";

export default {
  name: "submittal",
  description: "Generate a submittal PDF for a given project",
  async execute(message, args) {
    try {
      if (args.length === 0)
        return message.reply("❌ Please provide a project ID, e.g., `!submittal project_1760192314742`");

      const projectId = args[0].trim();

      const data = await fs.readJson("./data/projects.json").catch(() => ({}));
      const projects = Array.isArray(data.projects) ? data.projects : [];
      const project = projects.find((p) => p.id === projectId);

      if (!project)
        return message.reply(`❌ Project not found: ${projectId}`);

      const pdfPath = await generateSubmittal(projectId, project);

      await logSessionEvent(message.author.id, "Submittal Generated", {
        projectId,
        pdfPath,
      });

      const embed = new EmbedBuilder()
        .setColor(0x2f3136)
        .setTitle("📄 Submittal Generated")
        .addFields(
          { name: "Project ID", value: project.id, inline: false },
          { name: "Location", value: project.location || "N/A", inline: true },
          { name: "Building Type", value: project.buildingType || "N/A", inline: true },
          { name: "Stories", value: String(project.stories || "N/A"), inline: true },
          { name: "Estimated Cost", value: project.estimatedCost ? `$${project.estimatedCost.toLocaleString()}` : "N/A", inline: true }
        )
        .setTimestamp()
        .setFooter({ text: "Generated by Estimator AI V5" });

      await message.reply({ embeds: [embed], files: [pdfPath] });
    } catch (err) {
      console.error("[SUBMITTAL ERROR]", err);
      message.reply("❌ Failed to generate submittal.");
    }
  },
};
